import type { ProjectPlan, ResearchReport } from "@/lib/insights/types";

// ---------------------------------------------------------------------------
// Presentation-ready documentation export.
//
// Compiles a project's full copilot output — validation, research, plan, and
// resources — into a single self-contained Markdown brief that can be handed to
// a teammate, pasted into a doc/deck, or printed to PDF. Pure function (no Node
// APIs) so it runs on both server (export route) and client (in-session button).
// ---------------------------------------------------------------------------

export interface BriefInput {
  title: string;
  idea: string;
  createdAt?: number;
  validationMarkdown?: string | null;
  research?: ResearchReport | null;
  plan?: ProjectPlan | null;
}

export function buildMarkdownBrief(b: BriefInput): string {
  const out: string[] = [];
  const date = new Date(b.createdAt ?? Date.now()).toLocaleDateString();

  out.push(`# ${b.title}`, "");
  out.push(`> **Idea:** ${b.idea}`, `> `, `> _Generated by IdeaForge · ${date}_`, "");
  out.push(tableOfContents(b), "");

  if (b.validationMarkdown) {
    out.push("## 1. Problem Validation", "", b.validationMarkdown.trim(), "");
  }

  if (b.research) out.push(researchSection(b.research));
  if (b.plan) out.push(planSection(b.plan));

  out.push("---", "", "_This brief was assembled automatically. Verify sources before relying on them._");
  return out.join("\n");
}

function tableOfContents(b: BriefInput): string {
  const items: string[] = [];
  let n = 1;
  if (b.validationMarkdown) items.push(`${n++}. Problem Validation`);
  if (b.research) items.push(`${n++}. Research & Market Analysis`);
  if (b.plan) items.push(`${n++}. Project Plan`);
  return items.length ? "**Contents**\n\n" + items.map((i) => `- ${i}`).join("\n") : "";
}

function researchSection(r: ResearchReport): string {
  const s: string[] = ["## 2. Research & Market Analysis", ""];
  if (r.queries.length) s.push(`**Searches run:** ${r.queries.map((q) => `\`${q}\``).join(", ")}`, "");
  s.push(r.summaryMarkdown.trim(), "");

  if (r.existingSolutions.length) {
    s.push("### Existing solutions", "");
    for (const sol of r.existingSolutions) {
      s.push(`**${sol.name}** — ${sol.what}`);
      if (sol.strengths.length) s.push(`- ✅ Strengths: ${sol.strengths.join("; ")}`);
      if (sol.gaps.length) s.push(`- ⚠️ Gaps: ${sol.gaps.join("; ")}`);
      s.push("");
    }
  }

  if (r.gaps.length) {
    s.push("### Innovation opportunities", "");
    for (const g of r.gaps) s.push(`- **${g.title}** — ${g.description} → _${g.opportunity}_`);
    s.push("");
  }

  if (r.citations.length) {
    s.push("### Sources", "");
    for (const c of r.citations) s.push(`${c.id}. [${c.title}](${c.url}) — ${c.source}`);
    s.push("");
  }
  return s.join("\n");
}

function planSection(p: ProjectPlan): string {
  const s: string[] = ["## 3. Project Plan", "", `### ${p.title}`, "", p.pitch, ""];

  if (p.techStack.length) {
    s.push("### Recommended tech stack", "", "| Layer | Choice | Why |", "|---|---|---|");
    for (const t of p.techStack) s.push(`| ${t.category} | ${t.choice} | ${t.why} |`);
    s.push("");
  }

  if (p.architecture.length) {
    s.push("### Architecture", "");
    for (const c of p.architecture) {
      const links = c.connectsTo.length ? ` → ${c.connectsTo.join(", ")}` : "";
      s.push(`- **${c.name}** — ${c.responsibility}${links}`);
    }
    s.push("");
  }

  if (p.milestones.length) {
    s.push("### Roadmap & timeline", "");
    for (const m of p.milestones) {
      s.push(`**${m.phase}** — ${m.goal}`);
      if (m.tasks.length) s.push(...m.tasks.map((t) => `  - ${t}`));
      s.push(`  - _Deliverable: ${m.deliverable}_`, "");
    }
  }

  if (p.apis.length) {
    s.push("### APIs & services", "");
    for (const a of p.apis) s.push(`- **${a.name}** — ${a.purpose}${a.url ? ` (${a.url})` : ""}`);
    s.push("");
  }

  const resourceBlock = (label: string, items: ProjectPlan["repos"]) => {
    if (!items.length) return;
    s.push(`### ${label}`, "");
    for (const r of items) s.push(`- [${r.title}](${r.url})${r.description ? ` — ${r.description}` : ""}`);
    s.push("");
  };
  resourceBlock("GitHub repositories", p.repos);
  resourceBlock("Datasets", p.datasets);
  resourceBlock("Research papers", p.papers);

  if (p.clusters.length) {
    s.push("### Knowledge clusters", "");
    for (const c of p.clusters) {
      s.push(`**${c.theme}** — ${c.summary}`);
      s.push(...c.items.map((i) => `  - ${i}`), "");
    }
  }
  return s.join("\n");
}
