import PptxGenJS from "pptxgenjs";
import type { ProjectPlan, ResearchReport } from "@/lib/insights/types";

// ---------------------------------------------------------------------------
// Presentation-ready deck (.pptx) generation.
//
// Turns a project's copilot output into a real PowerPoint file — the
// "presentation-ready documentation" deliverable. Sections are emitted only
// when the underlying data exists, so partial projects still export cleanly.
// ---------------------------------------------------------------------------

export interface DeckInput {
  title: string;
  idea: string;
  validationMarkdown?: string | null;
  research?: ResearchReport | null;
  plan?: ProjectPlan | null;
}

const BRAND = "6D4AFF";
const INK = "1A1922";
const MUTED = "6B6A7B";

/** Strip markdown syntax so text renders cleanly in slide shapes. */
function plain(md: string): string {
  return md
    .replace(/```[\s\S]*?```/g, "")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/^#{1,6}\s*/gm, "")
    .replace(/[*_`>]/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Pull the most useful bullet lines out of the validation markdown. */
function validationBullets(md: string, max = 6): string[] {
  const text = plain(md);
  const lines = text
    .split("\n")
    .map((l) => l.replace(/^[-•]\s*/, "").trim())
    .filter((l) => l.length > 24 && l.length < 220);
  return lines.slice(0, max);
}

function clamp(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}

export async function buildPptxBuffer(input: DeckInput): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "IdeaForge";
  pptx.title = input.title;

  const addTitled = (heading: string) => {
    const slide = pptx.addSlide();
    slide.addText(heading, {
      x: 0.5,
      y: 0.35,
      w: 9,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: INK,
    });
    slide.addShape("rect", { x: 0.5, y: 0.95, w: 1.2, h: 0.05, fill: { color: BRAND } });
    return slide;
  };

  // --- Title slide ---------------------------------------------------------
  const cover = pptx.addSlide();
  cover.background = { color: "F7F7FB" };
  cover.addText(clamp(input.title, 90), {
    x: 0.6,
    y: 1.9,
    w: 8.8,
    h: 1.2,
    fontSize: 40,
    bold: true,
    color: INK,
  });
  cover.addText(clamp(input.idea, 180), {
    x: 0.6,
    y: 3.1,
    w: 8.8,
    h: 0.9,
    fontSize: 16,
    color: MUTED,
  });
  cover.addText("Generated by IdeaForge · iNSIGHTS Layer 2", {
    x: 0.6,
    y: 4.6,
    w: 8.8,
    h: 0.4,
    fontSize: 11,
    color: BRAND,
  });

  // --- Problem validation --------------------------------------------------
  if (input.validationMarkdown) {
    const bullets = validationBullets(input.validationMarkdown);
    if (bullets.length) {
      const s = addTitled("Problem Validation");
      s.addText(
        bullets.map((b) => ({ text: clamp(b, 200), options: { bullet: true, breakLine: true } })),
        { x: 0.6, y: 1.3, w: 8.8, h: 3.6, fontSize: 13, color: INK, lineSpacingMultiple: 1.2 },
      );
    }
  }

  // --- Research ------------------------------------------------------------
  const r = input.research;
  if (r) {
    if (r.summaryMarkdown) {
      const s = addTitled("Research & Market Analysis");
      s.addText(clamp(plain(r.summaryMarkdown), 900), {
        x: 0.6,
        y: 1.3,
        w: 8.8,
        h: 3.6,
        fontSize: 12,
        color: INK,
        lineSpacingMultiple: 1.25,
      });
    }

    if (r.existingSolutions.length) {
      const s = addTitled("Existing Solutions");
      const rows: PptxGenJS.TableRow[] = [
        [
          { text: "Solution", options: { bold: true, color: "FFFFFF", fill: { color: BRAND } } },
          { text: "Strengths", options: { bold: true, color: "FFFFFF", fill: { color: BRAND } } },
          { text: "Gaps", options: { bold: true, color: "FFFFFF", fill: { color: BRAND } } },
        ],
        ...r.existingSolutions.slice(0, 5).map((x) => [
          { text: clamp(x.name, 40) },
          { text: clamp((x.strengths ?? []).join("; "), 120) },
          { text: clamp((x.gaps ?? []).join("; "), 120) },
        ]),
      ];
      s.addTable(rows, {
        x: 0.5,
        y: 1.3,
        w: 9,
        fontSize: 10,
        color: INK,
        border: { type: "solid", color: "E7E6EF", pt: 1 },
      });
    }

    if (r.gaps.length) {
      const s = addTitled("Innovation Opportunities");
      s.addText(
        r.gaps.slice(0, 5).map((g) => ({
          text: `${g.title} — ${clamp(g.opportunity, 140)}`,
          options: { bullet: true, breakLine: true },
        })),
        { x: 0.6, y: 1.3, w: 8.8, h: 3.6, fontSize: 13, color: INK, lineSpacingMultiple: 1.3 },
      );
    }
  }

  // --- Plan ----------------------------------------------------------------
  const p = input.plan;
  if (p) {
    if (p.techStack.length) {
      const s = addTitled("Recommended Tech Stack");
      s.addText(
        p.techStack.slice(0, 8).map((t) => ({
          text: `${t.category}: ${t.choice} — ${clamp(t.why, 90)}`,
          options: { bullet: true, breakLine: true },
        })),
        { x: 0.6, y: 1.3, w: 8.8, h: 3.6, fontSize: 12, color: INK, lineSpacingMultiple: 1.25 },
      );
    }

    if (p.architecture.length) {
      const s = addTitled("Architecture");
      s.addText(
        p.architecture.slice(0, 7).map((c) => ({
          text: `${c.name} — ${clamp(c.responsibility, 110)}${
            c.connectsTo?.length ? ` → ${c.connectsTo.join(", ")}` : ""
          }`,
          options: { bullet: true, breakLine: true },
        })),
        { x: 0.6, y: 1.3, w: 8.8, h: 3.6, fontSize: 12, color: INK, lineSpacingMultiple: 1.25 },
      );
    }

    if (p.milestones.length) {
      const s = addTitled("Roadmap & Timeline");
      s.addText(
        p.milestones.slice(0, 6).flatMap((m) => [
          { text: m.phase, options: { bold: true, color: BRAND, breakLine: true } },
          {
            text: `${clamp(m.goal, 110)}  ·  Deliverable: ${clamp(m.deliverable, 70)}`,
            options: { breakLine: true, color: INK },
          },
        ]),
        { x: 0.6, y: 1.3, w: 8.8, h: 3.7, fontSize: 12, lineSpacingMultiple: 1.15 },
      );
    }

    const resources = [
      ...p.repos.slice(0, 3).map((x) => `Repo: ${clamp(x.title, 70)}`),
      ...p.datasets.slice(0, 3).map((x) => `Dataset: ${clamp(x.title, 70)}`),
      ...p.papers.slice(0, 3).map((x) => `Paper: ${clamp(x.title, 70)}`),
    ];
    if (resources.length) {
      const s = addTitled("Resources to Build With");
      s.addText(
        resources.map((t) => ({ text: t, options: { bullet: true, breakLine: true } })),
        { x: 0.6, y: 1.3, w: 8.8, h: 3.6, fontSize: 12, color: INK, lineSpacingMultiple: 1.25 },
      );
    }
  }

  // --- Sources -------------------------------------------------------------
  if (r?.citations.length) {
    const s = addTitled("Sources");
    s.addText(
      r.citations.slice(0, 10).map((c) => ({
        text: `[${c.id}] ${clamp(c.title, 80)} — ${c.source}`,
        options: { breakLine: true },
      })),
      { x: 0.6, y: 1.3, w: 8.8, h: 3.7, fontSize: 10, color: MUTED, lineSpacingMultiple: 1.2 },
    );
  }

  const out = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return out;
}
