import { AlertOctagon, CircleAlert, Info, ShieldCheck } from "lucide-react";
import { RULE_COUNT, type ConsistencyFinding, type ConsistencyReport, type FindingSeverity } from "@/lib/verify/consistency";

const STYLE: Record<FindingSeverity, { icon: typeof Info; className: string; label: string }> = {
  contradiction: { icon: AlertOctagon, className: "text-danger", label: "Contradiction" },
  gap: { icon: CircleAlert, className: "text-warning", label: "Gap" },
  note: { icon: Info, className: "text-muted", label: "Note" },
};

const WHERE: Record<ConsistencyFinding["where"], string> = {
  validation: "Validation",
  research: "Research",
  plan: "Plan",
  across: "Across artifacts",
};

/**
 * Whether the brief agrees with itself.
 *
 * Unlike every other check in this product, this one costs nothing — no
 * network, no model, no embeddings — so it is always on rather than sitting
 * behind a button. A check that has to be asked for is a check most briefs
 * never get.
 *
 * The clean state is shown as well as the failures, and that is deliberate. The
 * other panels stay quiet until asked; this one runs on every page load, so
 * silence would be indistinguishable from "not implemented" and the reader
 * would learn nothing from its absence.
 */
export default function ConsistencyCheck({ report }: { report: ConsistencyReport }) {
  if (report.ran === 0) return null;

  const contradictions = report.findings.filter((f) => f.severity === "contradiction").length;
  const clean = report.findings.length === 0;

  return (
    <section
      className={`rounded-2xl border p-4 ${
        contradictions > 0 ? "border-danger/40 bg-danger/5" : "border-border bg-card"
      }`}
    >
      <div className="flex flex-wrap items-center gap-2">
        <ShieldCheck className={`size-4 ${clean ? "text-success" : contradictions > 0 ? "text-danger" : "text-warning"}`} />
        <h2 className="text-sm font-semibold">Internal consistency</h2>
        <span className="text-[11px] text-muted">
          {report.ran} of {RULE_COUNT} checks ran
          {report.skipped > 0 && ` · ${report.skipped} need artifacts this project doesn’t have yet`}
        </span>
      </div>

      {clean ? (
        <p className="mt-1 text-xs text-success">
          The validation, research and plan do not contradict each other on anything these
          checks can see.
        </p>
      ) : (
        <>
          <p className="mt-1 max-w-prose text-xs text-muted">
            Each part of this brief was generated by a separate call, and nothing compared them
            until now. These are facts about the documents, not opinions about the idea.
          </p>
          <ul className="mt-3 space-y-1.5">
            {report.findings.map((f, i) => {
              const { icon: Icon, className, label } = STYLE[f.severity];
              return (
                <li
                  key={`${f.rule}-${i}`}
                  className="flex items-start gap-2 rounded-lg border border-border bg-surface p-2.5 text-xs"
                >
                  <Icon className={`mt-0.5 size-3.5 shrink-0 ${className}`} />
                  <span className="min-w-0">
                    <span className="leading-relaxed">{f.detail}</span>
                    <span className="mt-0.5 block text-[11px] text-muted">
                      <span className={className}>{label}</span> · {WHERE[f.where]} ·{" "}
                      <code className="text-[10px]">{f.rule}</code>
                    </span>
                  </span>
                </li>
              );
            })}
          </ul>
        </>
      )}
    </section>
  );
}
